# Generated by Django 4.2.14 on 2024-09-23 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_userprofile_alter_student_user_alter_teacher_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='student_images'),
        ),
        migrations.AddField(
            model_name='student',
            name='mobile',
            field=models.CharField(default='0123456789', max_length=10),
        ),
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='teacher_images'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='mobile',
            field=models.CharField(default='0123456789', max_length=10),
        ),
    ]
