# Generated by Django 4.2.14 on 2024-09-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_student_image_student_mobile_teacher_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('student', 'student'), ('teacher', 'teacher')], max_length=10),
        ),
    ]
