# Generated by Django 4.2.14 on 2024-10-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_classsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='teacher_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Pending', 'Pending')], default='Pending', max_length=10),
        ),
    ]
